[package]
name = "justarticles-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.1", features = ["full"] }
log4rs = "1.3.0"
log = "0.4.22"
axum = "0.7.5"
serde = "1.0.204"